//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro
    {
        public int id { get; set; }
        public string nome { get; set; }
        public byte[] foto { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public Nullable<int> fone { get; set; }
        public string cidade { get; set; }
        public Nullable<int> cep { get; set; }
        public string estado { get; set; }
        public string nomePai { get; set; }
        public string nomeMae { get; set; }
        public string nacionalidade { get; set; }
        public string naturalidade { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string estadoCivil { get; set; }
        public string grauInstrucao { get; set; }
        public Nullable<int> cedulaIdentidade { get; set; }
        public Nullable<int> carteiraProfissional { get; set; }
        public Nullable<int> carteiraReservista { get; set; }
        public Nullable<int> tituloEleitor { get; set; }
        public Nullable<int> carteiraHabilitacao { get; set; }
        public int cpf { get; set; }
    }
}
